[build]
  base = "matchmystack-fd/client"
  command = "npm install -g pnpm && pnpm install && pnpm run build:client"
  publish = "matchmystack-fd/client/dist/spa"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200